#!/bin/bash
# Office-31
python3 train_MBAN.py --gpu_id 0   --arch resnet50 --seed 0 --dset office --output_dir log/MBAN/Office31 --s_dset_path ~/workspace/Transfer/datasets/Office31/amazon.txt --t_dset_path ~/workspace/Transfer/datasets/Office31/webcam.txt --t_test_path ~/workspace/Transfer/datasets/Office31/webcam.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005  --mnd_tradeoff 1.5 --output_temp 1.0 --weight_type 1  --logit_temp 2.0  --cache-feature
python3 train_MBAN.py --gpu_id 0   --arch resnet50 --seed 0 --dset office --output_dir log/MBAN/Office31 --s_dset_path ~/workspace/Transfer/datasets/Office31/amazon.txt --t_dset_path ~/workspace/Transfer/datasets/Office31/dslr.txt --t_test_path ~/workspace/Transfer/datasets/Office31/dslr.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.003  --mnd_tradeoff 1.5 --output_temp 1.0 --weight_type 1  --logit_temp 2.0  --cache-feature
python3 train_MBAN.py --gpu_id 0   --arch resnet50 --seed 0 --dset office --output_dir log/MBAN/Office31 --s_dset_path ~/workspace/Transfer/datasets/Office31/webcam.txt --t_dset_path ~/workspace/Transfer/datasets/Office31/amazon.txt --t_test_path ~/workspace/Transfer/datasets/Office31/amazon.txt --epochs 40 --iters-per-epoch 500 --temp 10.0  --batch-size 36 --lr 0.005  --mnd_tradeoff 1.5 --output_temp 1.0 --weight_type 1  --logit_temp 2.0  --cache-feature
python3 train_MBAN.py --gpu_id 0   --arch resnet50 --seed 0 --dset office --output_dir log/MBAN/Office31 --s_dset_path ~/workspace/Transfer/datasets/Office31/dslr.txt --t_dset_path ~/workspace/Transfer/datasets/Office31/amazon.txt --t_test_path ~/workspace/Transfer/datasets/Office31/amazon.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005  --mnd_tradeoff 1.5 --output_temp 1.0 --weight_type 1  --logit_temp 2.0  --cache-feature
python3 train_MBAN.py --gpu_id 0   --arch resnet50 --seed 0 --dset office --output_dir log/MBAN/Office31 --s_dset_path ~/workspace/Transfer/datasets/Office31/dslr.txt --t_dset_path ~/workspace/Transfer/datasets/Office31/webcam.txt --t_test_path ~/workspace/Transfer/datasets/Office31/webcam.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005  --mnd_tradeoff 1.5 --output_temp 1.0 --weight_type 1  --logit_temp 2.0  --cache-feature
python3 train_MBAN.py --gpu_id 0   --arch resnet50 --seed 0 --dset office --output_dir log/MBAN/Office31 --s_dset_path ~/workspace/Transfer/datasets/Office31/webcam.txt --t_dset_path ~/workspace/Transfer/datasets/Office31/dslr.txt --t_test_path ~/workspace/Transfer/datasets/Office31/dslr.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005  --mnd_tradeoff 1.5 --output_temp 1.0 --weight_type 1  --logit_temp 2.0  --cache-feature

# Office-Home
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Art.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Clipart.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Art.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Product.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Art.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Real_World.txt --epochs 40 --iters-per-epoch 500 --temp 10.0  --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Clipart.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Art.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Clipart.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Product.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Clipart.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Real_World.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Product.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Art.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Product.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Clipart.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Product.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Real_World.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Real_World.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Art.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Real_World.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Clipart.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature
# python3 train_MBAN.py --gpu_id 1 --arch resnet50 --seed 0 --dset office-home --output_dir log/MBAN/home --s_dset_path ~/workspace/Transfer/datasets/Office-Home/Real_World.txt --t_dset_path ~/workspace/Transfer/datasets/Office-Home/Product.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 1.5 --weight_type 1 --logit_temp 2.0 --cache-feature

# VisDA2017
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --seed 0 --dset visda2017 --output_dir log/MBAN/visda2017 --s_dset_path ~/workspace/Transfer/datasets/VisDA2017/train.txt --t_dset_path ~/workspace/Transfer/datasets/VisDA2017/validation.txt --epochs 40 --iters-per-epoch 500 --temp 10.0 --batch-size 36 --lr 0.005 --mnd_tradeoff 2.0 --weight_type 1 --center_crop --logit_temp 2.0 --cache-feature 

# domainnet
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/clipart_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/infograph_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/clipart_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/painting_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/clipart_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/clipart_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/real_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/real_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/clipart_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/sketch_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/infograph_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/clipart_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/infograph_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/painting_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/infograph_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/infograph_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/real_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/real_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/infograph_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/sketch_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/painting_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/clipart_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/painting_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/infograph_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/painting_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/painting_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/real_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/real_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/painting_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/sketch_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/clipart_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/infograph_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/painting_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/real_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/real_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/sketch_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0   --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/real_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/clipart_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/real_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/infograph_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/real_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/painting_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/real_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/real_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/sketch_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/sketch_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/clipart_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/sketch_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/infograph_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/sketch_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/painting_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/sketch_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
# python3 train_MBAN.py --gpu_id 0 --arch resnet101 --center_crop --seed 1 --dset domainnet --output_dir log/MBAN/domainnet --s_dset_path ~/workspace/Transfer/datasets/DomainNet/sketch_train.txt --t_dset_path ~/workspace/Transfer/datasets/DomainNet/real_train.txt --t_test_path ~/workspace/Transfer/datasets/DomainNet/real_test.txt --epochs 30 --iters-per-epoch 1000 --temp 10.0 --lr 0.005  --weight_type 1 --mnd_tradeoff 2.0 --batch-size 64 --logit_temp 2.0 --cache-feature 
